### ISSUE TITLE
CPython 3.5 manylinux s390x failed

### ISSUE THREAD

**Issue by caishanli** [pypa/cibuildwheel#658]
Hi, I use cibuildwheel to build [ncnn](https://github.com/Tencent/ncnn), build log is [here](https://github.com/Tencent/ncnn/runs/2524175576?check_suite_focus=true), and workflow file is [release-python.yml](https://github.com/Tencent/ncnn/blob/master/.github/workflows/release-python.yml)

**Comment by Czaki** [comment]
It looks like lack of SSL library in docker image. Could You fix it using `yum install` for the proper package.

**Comment by caishanli** [comment]
> It looks like lack of SSL library in docker image. Could You fix it using `yum install` for the proper package.

error msg is ERROR: Could not build wheels for cmake which use PEP 517 and cannot be installed directly
You mean install cmake via yum?

**Comment by henryiii** [comment]
These are being added soon, see https://github.com/scikit-build/cmake-python-distributions/pull/130 - but for now, you can turn them off when building on s390x in your pyproject.yaml via a selector and use the built-in CMake in those images instead.

**Comment by henryiii** [comment]
(You should also be able to add the requirements for CMake to build from SDist, which also would fix it - I expect it's SSL that's missing?)

**Comment by henryiii** [comment]
Why are you shipping 3.5 + s390x? Shouldn't you start with 3.6? We are currently dropping 3.5 and 3.5 has already been removed from the manylinux images already, including s390x images.

**Comment by caishanli** [comment]
> Why are you shipping 3.5 + s390x? Shouldn't you start with 3.6? We are currently dropping 3.5 and 3.5 has already been removed from the manylinux images already, including s390x images.

3.5+s390x is auto build
yml is [here](https://github.com/Tencent/ncnn/blob/master/.github/workflows/release-python.yml), anything wrong?

**Comment by caishanli** [comment]
> Something roughly like this should work for your pyproject.toml until new wheels are released. I'm only guessing Ninja has similar issues.
> 
> ```toml
> [build-system]
> requires = [
>     "setuptools>=42",
>     "wheel",
>     "ninja; sys_platform != 'win32' and platform_machine != 'aarch64'",
>     "cmake>=3.12; platform_machine != 'aarch64'",
> ]
> build-backend = "setuptools.build_meta"
> ```

ninja is ok on aarch64, see build log [here](https://github.com/Tencent/ncnn/runs/2525339711?check_suite_focus=true)

**Comment by henryiii** [comment]
Oops, please replace aarch64 with s390x above. 😳

**Comment by caishanli** [comment]
> Oops, please replace aarch64 with s390x above.

still failed with s390x, see [log](https://github.com/Tencent/ncnn/pull/2892/checks?check_run_id=2533247442)

**Comment by mayeut** [comment]
Only the build for CMake wheel was failing in the original log so I guess you can still rely on Ninja being built from source correctly and use the manylinux provided cmake:
```
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ninja; sys_platform != 'win32'",
    "cmake>=3.12; platform_machine != 's390x'",
]
build-backend = "setuptools.build_meta"
```

**Comment by henryiii** [comment]
I just released CMake 3.20.2 which contains Apple Silicon, S390x, and PowerPC builds now too (thanks to @mayeut). So this should "just work" now (though Ninja may still need some work).

**Comment by henryiii** [comment]
Closable, @caishanli?

**Comment by caishanli** [comment]
in testing now... 
aarch64 takes long time to build
and i will report the result

**Comment by caishanli** [comment]
> Closable, @caishanli?

still failed. see build log [here](https://github.com/Tencent/ncnn/pull/2972/checks?check_run_id=2725449020)

**Comment by mayeut** [comment]
> see build log here

@caishanli,
The error is now completely different. All tools seem to install correctly.
The `CMakeLists.txt` [has a fallback to x86 arch with sse2 enabled](https://github.com/Tencent/ncnn/blob/1cb3eecd70c22e60b3bb910682d956dc6460ad2c/CMakeLists.txt#L164)
This is what is now failing:
```
/opt/rh/devtoolset-9/root/usr/bin/c++  -I../../src/layer/x86 -I../../src -Isrc -I../../src/layer -O3 -DNDEBUG -fPIC -DNCNN_STATIC_DEFINE -Wall -Wextra -Wno-unused-function -Ofast -ffast-math -fvisibility=hidden -fvisibility-inlines-hidden -msse2 -msse -fopenmp -pthread -MD -MT src/CMakeFiles/ncnn.dir/allocator.cpp.o -MF src/CMakeFiles/ncnn.dir/allocator.cpp.o.d -o src/CMakeFiles/ncnn.dir/allocator.cpp.o -c ../../src/allocator.cpp
929
    c++: error: unrecognized command line option ‘-msse2’
930
    c++: error: unrecognized command line option ‘-msse’
```

**Comment by mayeut** [comment]
fixed by https://github.com/Tencent/ncnn/pull/3396 which indeed includes a fix in `CMakeLists.txt`.
